program lpt1;

uses crt, printer;

begin
clrscr;
{writeln;}
{writeln( '' );}

writeln;
writeln( lst, '-------' );
writeln;
writeln( lst, '-' );
writeln;
writeln( lst, '-' );
writeln;
writeln( lst, '-' );

writeln( lst, '-' );

writeln( lst, '-' );

writeln( lst, '-' );

writeln( lst, '-' );


writeln( lst, '|' );

writeln( lst, '|' );


writeln( lst, '\' );


writeln( lst, '/' );

writeln( lst, '/' );
writeln( lst, 'this is jason nom' );

delay(500);
clrscr;
writeln(lst );
writeln( lst,  '_ _ _ _ _ _ ',' _ _ _ _ _ ' );
writeln(  lst, 'sign your name here and fill in   today"s date here' );


end.