Program dostest;

uses crt, dos;

var
Key : char;
eat : string;

begin
clrscr;
writeln( 'sound test will begin now' );
readln;
sound(540);
writeln( 'your sound is working if you here a sound' );
readln;
nosound;
writeln( 'now going to colour test' );
readln;
textcolor(0);
writeln( 'if you see different colours on the screen than it is working' );
readln;
textcolor(1);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(2);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(3);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(4);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(5);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(6);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(7);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(8);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(9);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(10);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(11);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(12);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(13);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(14);
writeln( 'if you see different colours on the screen than it is working' );
readln;textcolor(15);
writeln( 'if you see different colours on the screen than it is working' );
readln;
clrscr;
end.